
const ActionTypes = {
    // Items All Action Types
    ITEM_LIST_REQUEST: "ITEM_LIST_REQUEST",
    ITEM_LIST_OK: "ITEM_LIST_OK",
    ITEM_LIST_X: "ITEM_LIST_X",
    // Item Details Action Types
    ITEM_DETAIL_REQUEST: "ITEM_DETAIL_REQUEST",
    ITEM_DETAIL_OK: "ITEM_DETAIL_OK",
    ITEM_DETAIL_X: "ITEM_DETAIL_X", 
    // Shopping Basket Action Types
    BASKET_ADD_ITEM_REQ: "BASKET_ADD_ITEM_REQ",
    BASKET_ADD_ITEM_OK: "BASKET_ADD_ITEM_OK",
    BASKET_ADD_ITEM_X: "BASKET_ADD_ITEM_X",
    
    BASKET_REMOVE_ITEM_REQ: "BASKET_REMOVE_ITEM",
    BASKET_REMOVE_ITEM_OK: "BASKET_REMOVE_ITEM_OK",
    BASKET_REMOVE_ITEM_X: "BASKET_REMOVE_ITEM_X",
  };
  
  export default ActionTypes;